apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.34.2
appVersion: 4.23.1-20240820
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: 2.15.1
  name: keda
  condition: autoscaling.enabled, keda.enabled
- repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.2
  name: ingress-nginx
  condition: ingress.enabled, ingress-nginx.enabled
- repository: https://jaegertracing.github.io/helm-charts
  version: 3.1.2
  name: jaeger
  condition: tracing.enabled, jaeger.enabled
- repository: https://prometheus-community.github.io/helm-charts
  version: 62.0.0
  name: kube-prometheus-stack
  condition: monitoring.enabled, prometheus-stack.enabled
maintainers:
  - name: SeleniumHQ
    email: selenium-developers@googlegroups.com
sources:
  - https://github.com/SeleniumHQ/docker-selenium
