apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.12.1
appVersion: 4.5.3-20221024
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
