# To execute this docker compose yml file use `docker compose -f docker-compose-v3-video-upload-standalone.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-video-upload-standalone.yml down`
# ${variable_pattern} get value from .env in the same directory
version: "3"
services:
  # Start a local FTP server to demonstrate video upload with RCLONE (https://github.com/delfer/docker-alpine-ftp-server)
  ftp_server:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp_server
    environment:
      - USERS=seluser|selenium.dev
    volumes:
      # Mount the local directory `/home/${USER}/Videos/upload` to the FTP server's `/ftp/seluser` directory to check out the uploaded videos
      - /tmp/upload:/ftp/seluser
    command: ["/bin/sh", "-c", "/sbin/tini -- /bin/start_vsftpd.sh && tail -f /dev/null"]
    stop_grace_period: 30s

  standalone_chrome:
    image: selenium/standalone-chrome:4.24.0-20240907
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium

  standalone_edge:
    image: selenium/standalone-edge:4.24.0-20240907
    shm_size: 2gb
    ports:
      - "5444:4444"
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium

  standalone_firefox:
    image: selenium/standalone-firefox:4.24.0-20240907
    shm_size: 2gb
    ports:
      - "6444:4444"
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium

  chrome_video:
    image: selenium/video:ffmpeg-7.0.2-20240907
    depends_on:
      - standalone_chrome
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium
      - SE_VIDEO_RECORD_STANDALONE=true
      - DISPLAY_CONTAINER_NAME=standalone_chrome
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_UPLOAD_ENABLED=true
      # Remote name and destination path to upload
      - SE_UPLOAD_DESTINATION_PREFIX=myftp://ftp/seluser
      # All configs required for RCLONE to upload to remote name myftp
      - RCLONE_CONFIG_MYFTP_TYPE=ftp
      - RCLONE_CONFIG_MYFTP_HOST=ftp_server
      - RCLONE_CONFIG_MYFTP_PORT=21
      - RCLONE_CONFIG_MYFTP_USER=seluser
      # Password encrypted using command: rclone obscure <your_password>
      - RCLONE_CONFIG_MYFTP_PASS=KkK8RsUIba-MMTBUSnuYIdAKvcnFyLl2pdhQig
      - RCLONE_CONFIG_MYFTP_FTP_CONCURRENCY=10
    stop_grace_period: 30s

  edge_video:
    image: selenium/video:ffmpeg-7.0.2-20240907
    depends_on:
      - standalone_edge
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium
      - SE_VIDEO_RECORD_STANDALONE=true
      - DISPLAY_CONTAINER_NAME=standalone_edge
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_UPLOAD_ENABLED=true
      # Remote name and destination path to upload
      - SE_UPLOAD_DESTINATION_PREFIX=myftp://ftp/seluser
      # All configs required for RCLONE to upload to remote name myftp
      - RCLONE_CONFIG_MYFTP_TYPE=ftp
      - RCLONE_CONFIG_MYFTP_HOST=ftp_server
      - RCLONE_CONFIG_MYFTP_PORT=21
      - RCLONE_CONFIG_MYFTP_USER=seluser
      # Password encrypted using command: rclone obscure <your_password>
      - RCLONE_CONFIG_MYFTP_PASS=KkK8RsUIba-MMTBUSnuYIdAKvcnFyLl2pdhQig
      - RCLONE_CONFIG_MYFTP_FTP_CONCURRENCY=10
    stop_grace_period: 30s

  firefox_video:
    image: selenium/video:ffmpeg-7.0.2-20240907
    depends_on:
      - standalone_firefox
    environment:
      - SE_ROUTER_USERNAME=admin
      - SE_ROUTER_PASSWORD=admin
      - SE_SUB_PATH=/selenium
      - SE_VIDEO_RECORD_STANDALONE=true
      - DISPLAY_CONTAINER_NAME=standalone_firefox
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_UPLOAD_ENABLED=true
      # Remote name and destination path to upload
      - SE_UPLOAD_DESTINATION_PREFIX=myftp://ftp/seluser
      # All configs required for RCLONE to upload to remote name myftp
      - RCLONE_CONFIG_MYFTP_TYPE=ftp
      - RCLONE_CONFIG_MYFTP_HOST=ftp_server
      - RCLONE_CONFIG_MYFTP_PORT=21
      - RCLONE_CONFIG_MYFTP_USER=seluser
      # Password encrypted using command: rclone obscure <your_password>
      - RCLONE_CONFIG_MYFTP_PASS=KkK8RsUIba-MMTBUSnuYIdAKvcnFyLl2pdhQig
      - RCLONE_CONFIG_MYFTP_FTP_CONCURRENCY=10
    stop_grace_period: 30s
