# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-video.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-video.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20220609
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - SE_DISPLAY_CONTAINER_NAME=chrome
      - SE_FILE_NAME=chrome_video.mp4

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20220609
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - edge
    environment:
      - SE_DISPLAY_CONTAINER_NAME=edge
      - SE_FILE_NAME=edge_video.mp4

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20220609
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - SE_DISPLAY_CONTAINER_NAME=firefox
      - SE_FILE_NAME=firefox_video.mp4

  selenium-hub:
    image: selenium/hub:4.2.2-20220609
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
