version: 2.1

workflows:
  build-and-test-multi-arch:
    jobs:
      - kubernetes-test:
          name: "K8s test - Playwright Connect Autoscaling Grid"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.25.16'
          test-strategy: playwright_connect_grid
          cluster: 'minikube'
          helm-version: 'v3.10.3'
          docker-version: '24.0.9'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling disabled"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.26.15'
          test-strategy: disabled
          cluster: 'minikube'
          helm-version: 'v3.11.3'
          docker-version: '24.0.9'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling Jobs"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.27.16'
          test-strategy: job
          cluster: 'minikube'
          helm-version: 'v3.12.3'
          docker-version: '24.0.9'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling Deployments"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.28.15'
          test-strategy: deployment
          cluster: 'minikube'
          helm-version: 'v3.13.3'
          docker-version: '24.0.9'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling Jobs - HTTPS"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.29.10'
          test-strategy: job_https
          cluster: 'minikube'
          helm-version: 'v3.14.3'
          docker-version: '25.0.5'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling Jobs - Ingress hostname"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.30.6'
          test-strategy: job_hostname
          cluster: 'minikube'
          helm-version: 'v3.15.4'
          docker-version: '26.1.4'
          test-upgrade: true
      - kubernetes-test:
          name: "K8s test - Autoscaling Deployments - HTTPS"
          platforms: linux/arm64
          machine-type: ubuntu2204arm64large
          k8s-version: 'v1.31.2'
          test-strategy: deployment_https
          cluster: 'minikube'
          helm-version: 'v3.16.1'
          docker-version: '27.2.0'
          test-upgrade: true
      - docker-test:
          name: "Docker test - Use random user (true)"
          test-strategy: test
          use-random-user: true
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: false
          enable-managed-downloads: false
      - docker-test:
          name: "Docker test - Use random user (false)"
          test-strategy: test
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: false
          enable-managed-downloads: false
      - docker-test:
          name: "Docker test - Video recording"
          test-strategy: test_video
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true
      - docker-test:
          name: "Docker test - Video recording dynamic file name"
          test-strategy: test_video_dynamic_name
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true
      - docker-test:
          name: "Docker test - Video recording standalone"
          test-strategy: test_video_standalone
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true
      - docker-test:
          name: "Docker test - Dynamic Grid"
          test-strategy: test_node_docker
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: false
      - docker-test:
          name: "Docker test - Dynamic Grid Standalone"
          test-strategy: test_standalone_docker
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true
      - docker-test:
          name: "Docker test - Parallel execution"
          test-strategy: test_parallel
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true
      - docker-test:
          name: "Docker test - Node relay commands"
          test-strategy: test_node_relay
          use-random-user: false
          platforms: linux/arm64
          machine-type: ubuntu2204arm64
          firefox-install-lang-package: true
          enable-managed-downloads: true

executors:
  ubuntu2204arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
  ubuntu2204arm64large:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.large

jobs:
  docker-test:
    parameters:
      platforms:
        type: string
      machine-type:
        type: executor
      test-strategy:
        type: string
      use-random-user:
        type: boolean
      firefox-install-lang-package:
        type: boolean
      enable-managed-downloads:
        type: boolean
    executor: << parameters.machine-type >>
    environment:
      NAMESPACE: selenium
      BUILD_DATE: today
      PLATFORMS: << parameters.platforms >>
      TEST_STRATEGY: << parameters.test-strategy >>
      USE_RANDOM_USER: << parameters.use-random-user >>
      TEST_FIREFOX_INSTALL_LANG_PACKAGE: << parameters.firefox-install-lang-package >>
      SELENIUM_ENABLE_MANAGED_DOWNLOADS: << parameters.enable-managed-downloads >>
    steps:
      - run:
          name: "Prepare workflow environment variables"
          command: |
            echo 'export BRANCH="${CIRCLE_BRANCH//\//-}"' >> $BASH_ENV
            cat $BASH_ENV
            source $BASH_ENV
      - checkout
      - run:
          name: "Setup environment"
          command: |
            make setup_dev_env
      - run:
          name: "Print system info"
          command: |
            uname -a
            docker info
      - run:
          name: "Build Docker images"
          command: |
            N=3
            while [ $N -gt 0 ]; do
              output=$(eval "PLATFORMS=${PLATFORMS} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} make build")
              status=$?
              if [ $status -eq 0 ]; then
                echo "Build images passed"
                exit 0
              else
                echo "Build failed. Retrying..."
                N=$((N-1))
                sleep 10
              fi
            done
            exit 1
      - run:
          name: "Test Docker images"
          command: |
            N=3
            while [ $N -gt 0 ]; do
              output=$(eval "USE_RANDOM_USER_ID=${USE_RANDOM_USER} PLATFORMS=${PLATFORMS} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} \
              TEST_FIREFOX_INSTALL_LANG_PACKAGE=${TEST_FIREFOX_INSTALL_LANG_PACKAGE} SELENIUM_ENABLE_MANAGED_DOWNLOADS=${SELENIUM_ENABLE_MANAGED_DOWNLOADS} \
              make ${TEST_STRATEGY}")
              status=$?
              if [ $status -eq 0 ]; then
                echo "Tests passed"
                exit 0
              else
                echo "Tests failed. Retrying..."
                N=$((N-1))
                sleep 10
              fi
            done
            exit 1

  kubernetes-test:
    parameters:
      platforms:
        type: string
      machine-type:
        type: executor
      k8s-version:
        type: string
      test-strategy:
        type: string
      cluster:
        type: string
      helm-version:
        type: string
      docker-version:
        type: string
      test-upgrade:
        type: boolean
    executor: << parameters.machine-type >>
    environment:
      NAMESPACE: selenium
      BUILD_DATE: today
      PLATFORMS: << parameters.platforms >>
      TEST_STRATEGY: << parameters.test-strategy >>
      CLUSTER: << parameters.cluster >>
      KUBERNETES_VERSION: << parameters.k8s-version >>
      HELM_VERSION: << parameters.helm-version >>
      DOCKER_VERSION: << parameters.docker-version >>
      TEST_UPGRADE_CHART: << parameters.test-upgrade >>
    steps:
      - run:
          name: "Prepare workflow environment variables"
          command: |
            echo 'export BRANCH="${CIRCLE_BRANCH//\//-}"' >> $BASH_ENV
            cat $BASH_ENV
            source $BASH_ENV
      - run:
          name: "Print system info"
          command: |
            uname -a
            docker info
      - checkout
      - run:
          name: "Set up Kubernetes environment"
          command: |
            make setup_dev_env
            CLUSTER=${CLUSTER} KUBERNETES_VERSION=${KUBERNETES_VERSION} NAME=${NAMESPACE} VERSION=${BRANCH} \
            BUILD_DATE=${BUILD_DATE} make chart_cluster_setup
      - run:
          name: "Build Docker images"
          no_output_timeout: 30m
          command: |
            N=3
            while [ $N -gt 0 ]; do
              output=$(eval "PLATFORMS=${PLATFORMS} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} make build")
              status=$?
              if [ $status -eq 0 ]; then
                echo "Build images passed"
                exit 0
              else
                echo "Build failed. Retrying..."
                N=$((N-1))
                sleep 10
              fi
            done
            exit 1
      - run:
          name: "Build Helm charts"
          command: |
            BUILD_DATE=${BUILD_DATE} make chart_build
            echo "export CHART_PACKAGE_PATH=$(cat /tmp/selenium_chart_version)" >> $BASH_ENV
            echo "export CHART_FILE_NAME=$(basename $(cat /tmp/selenium_chart_version))" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: "Test Selenium Grid on Kubernetes"
          no_output_timeout: 30m
          command: |
            if [ "${TEST_STRATEGY}" == "playwright_connect_grid" ]; then
              PLATFORMS=${PLATFORMS} NAME=${IMAGE_REGISTRY} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} TEST_UPGRADE_CHART=false make chart_test_autoscaling_${TEST_STRATEGY} && make test_video_integrity
              exit $?
            fi
            N=3
            while [ $N -gt 0 ]; do
              output=$(eval "PLATFORMS=${PLATFORMS} NAME=${IMAGE_REGISTRY} VERSION=${BRANCH} BUILD_DATE=${BUILD_DATE} TEST_UPGRADE_CHART=false make chart_test_autoscaling_${TEST_STRATEGY} && make test_video_integrity")
              status=$?
              if [ $status -eq 0 ]; then
                echo "${output}"
                echo "Tests passed"
                exit 0
              else
                echo "${output}"
                echo "Tests failed. Retrying..."
                N=$((N-1))
                sleep 10
              fi
            done
            exit 1
      - run:
          name: "Clean-up Kubernetes environment"
          command: |
            CLUSTER=${CLUSTER} make chart_cluster_cleanup
