[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.0.0-beta-1-prerelease-20210201", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0-beta-1-prerelease-20210201", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-opera:4.0.0-beta-1-prerelease-20210201", "{\"browserName\": \"operablink\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
host = "tcp://host.docker.internal:2375"
