[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.0.0-beta-2-20210319", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0-beta-2-20210319", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-opera:4.0.0-beta-2-20210319", "{\"browserName\": \"operablink\"}"
]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
host = "tcp://host.docker.internal:2375"
# Docker imagee used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20210319"
# Absolute path where test assets will be stored (this path must exist on the host)
assets-path = "/assets/path/on/your/host/machine"
# Absolute path where test assets will be stored inside the container
# "/opt/selenium/assets" already exists inside the containers
# If you want to use another one, be sure it exists.
container-assets-path = "/opt/selenium/assets"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#hostname = <ip-from-node-machine>
#port = <port-from-node-machine>
