{{- if and .Values.chromeNode.enabled (include "seleniumGrid.useKEDA" .) (eq .Values.autoscaling.scalingType "job") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: selenium-chrome-node
    app.kubernetes.io/name: selenium-chrome-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.chromeNode.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  maxReplicaCount: {{ .Values.chromeNode.maxReplicaCount }}
  {{- with .Values.autoscaling.scaledJobOptions -}}
    {{ toYaml . | nindent 2 }}
  {{- end }}
  triggers:
    - type: selenium-grid
    {{- with .Values.chromeNode.hpa }}
      metadata: {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 0
{{- $podScope := deepCopy . -}}
{{- $_ := set $podScope "name" "selenium-chrome-node" -}}
{{- $_ =  set $podScope "node" .Values.chromeNode  -}}
{{- include "seleniumGrid.podTemplate" $podScope | nindent 4 }}
{{- end }}
