{{- if and .Values.chromeNode.enabled (eq (include "seleniumGrid.useKEDA" .) "true") (eq .Values.autoscaling.scalingType "deployment") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: {{ .Release.Namespace }}
  labels:
    deploymentName: {{ template "seleniumGrid.chromeNode.fullname" . }}
spec:
  maxReplicaCount: {{ .Values.chromeNode.maxReplicaCount }}
  scaleTargetRef:
    name: {{ template "seleniumGrid.chromeNode.fullname" . }}
  triggers:
    - type: selenium-grid
    {{- with .Values.chromeNode.hpa }}
      metadata: {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
{{- end }}
