{{- if and .Values.edgeNode.enabled (eq (include "seleniumGrid.useKEDA" .) "true") (eq .Values.autoscaling.scalingType "deployment") }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "seleniumGrid.edgeNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: delete
    {{- with .Values.autoscaling.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    deploymentName: {{ template "seleniumGrid.edgeNode.fullname" . }}
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.edgeNode.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- $podScope := deepCopy . -}}
  {{- $_ := set $podScope "name" (include "seleniumGrid.edgeNode.fullname" .) -}}
  {{- $_ =  set $podScope "node" .Values.edgeNode -}}
  {{- include "seleniumGrid.autoscalingTemplate" $podScope | nindent 2 }}
{{- end }}
