{{- if .Values.isolateComponents }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "seleniumGrid.eventBus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &event_bus_labels
    app: {{ template "seleniumGrid.eventBus.fullname" . }}
    app.kubernetes.io/name: {{ template "seleniumGrid.eventBus.fullname" . }}
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  strategy:
    {{- template "seleniumGrid.updateStrategy" (list $.Values.components.eventBus $.Values.global.seleniumGrid) }}
  replicas: 1
  revisionHistoryLimit: {{ .Values.global.seleniumGrid.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "seleniumGrid.eventBus.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: *event_bus_labels
      annotations:
        checksum/logging-configmap: {{ include (print $.Template.BasePath "/logging-configmap.yaml") . | sha256sum }}
        checksum/server-configmap: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    {{- with .Values.components.eventBus.annotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ template "seleniumGrid.serviceAccount.fullname" . }}
      serviceAccount: {{ template "seleniumGrid.serviceAccount.fullname" . }}
      containers:
        - name: {{ template "seleniumGrid.eventBus.fullname" . }}
          {{- $imageTag := default .Values.global.seleniumGrid.imageTag .Values.components.eventBus.imageTag }}
          {{- $imageRegistry := default .Values.global.seleniumGrid.imageRegistry .Values.components.eventBus.imageRegistry }}
          image: {{ printf "%s/%s:%s" $imageRegistry .Values.components.eventBus.imageName $imageTag }}
          imagePullPolicy: {{ .Values.components.eventBus.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.components.eventBus.port }}
              protocol: TCP
            - containerPort: {{ .Values.components.eventBus.publishPort }}
              protocol: TCP
            - containerPort: {{ .Values.components.eventBus.subscribePort }}
              protocol: TCP
          env:
            - name: SE_OTEL_SERVICE_NAME
              value: '{{ template "seleniumGrid.eventBus.fullname" . }}'
            - name: SE_EVENT_BUS_HOST
              value: '{{ template "seleniumGrid.eventBus.fullname" . }}.{{ .Release.Namespace }}'
            - name: SE_EVENT_BUS_PORT
              value: {{ .Values.components.eventBus.port | quote }}
        {{- with .Values.components.extraEnvironmentVariables }}
            {{- tpl (toYaml .) $ | nindent 12 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "seleniumGrid.logging.configmap.fullname" . }}
            - configMapRef:
                name: {{ template "seleniumGrid.server.configmap.fullname" . }}
            - secretRef:
                name: {{ template "seleniumGrid.common.secrets.fullname" . }}
          {{- with .Values.components.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
            - name: {{ include "seleniumGrid.tls.fullname" .  | quote }}
              mountPath: {{ .Values.tls.certVolumeMountPath | quote }}
              readOnly: true
          {{- end }}
        {{- with .Values.components.eventBus.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.components.eventBus.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.components.eventBus.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.affinity .Values.components.eventBus.affinity }}
      {{- $affinityYaml := default .Values.global.seleniumGrid.affinity .Values.components.eventBus.affinity }}
      affinity: {{- toYaml $affinityYaml | nindent 8 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.topologySpreadConstraints .Values.components.distributor.topologySpreadConstraints }}
      {{- $topologySpreadConstraints := default .Values.global.seleniumGrid.topologySpreadConstraints .Values.components.distributor.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range $constraint := $topologySpreadConstraints }}
        - {{ toYaml $constraint | nindent 10 | trim }}
        {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              app: {{ template "seleniumGrid.eventBus.fullname" $ }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.components.eventBus.tolerations }}
      tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.imagePullSecret .Values.components.eventBus.imagePullSecret }}
      imagePullSecrets:
        - name: {{ default .Values.global.seleniumGrid.imagePullSecret .Values.components.eventBus.imagePullSecret }}
    {{- end }}
    {{- with .Values.components.eventBus.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
      volumes:
      {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
        - name: {{ include "seleniumGrid.tls.fullname" .  | quote }}
          secret:
            secretName: {{ include "seleniumGrid.tls.fullname" .  | quote }}
      {{- end }}
{{- end }}
