{{- if .Values.ingress.enabled }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "seleniumGrid.ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $ingressAnnotations := (include "seleniumGrid.ingress.nginx.annotations.default" . | toString | fromYaml ) }}
  {{- with .Values.ingress.annotations -}}
    {{- $ingressAnnotations = mergeOverwrite $ingressAnnotations . }}
  {{- end }}
  {{- if not (empty $ingressAnnotations) }}
  annotations:
    {{- $ingressAnnotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and (or .Values.tls.enabled .Values.tls.ingress.generateTLS) .Values.ingress.hostname (not .Values.ingress.tls) }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ include "seleniumGrid.tls.fullname" . | quote }}
  {{- else if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ tpl (.secretName) $ | quote }}
    {{- end }}
  {{- end }}
  rules:
      {{- if $.Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
      {{- else }}
    - http:
      {{- end }}
      {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version }}
        paths:
        {{- if empty (.Values.ingress.paths) }}
          - path: {{ $.Values.ingress.path | default "/" }}
            pathType: {{ $.Values.ingress.pathType | default "Prefix" }}
            backend:
              service:
                {{- if $.Values.isolateComponents }}
                name: {{ template "seleniumGrid.router.fullname" $ }}
                port:
                  number: {{ $.Values.components.router.port }}
                {{- else }}
                name: {{ template "seleniumGrid.hub.fullname" $ }}
                port:
                  number: {{ $.Values.hub.port }}
                {{- end }}
        {{- else }}
          {{- tpl (toYaml .Values.ingress.paths | nindent 10) . }}
        {{- end }}
      {{- else }}
        paths:
          - path: /
            backend:
              {{- if $.Values.isolateComponents }}
              serviceName: {{ template "seleniumGrid.router.fullname" $ }}
              servicePort: {{ $.Values.components.router.port }}
              {{- else }}
              serviceName: {{ template "seleniumGrid.hub.fullname" $ }}
              servicePort: {{ $.Values.hub.port }}
              {{- end }}
      {{- end }}
{{- end }}
