apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seleniumGrid.node.configmap.fullname" $ }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.nodeConfigMap.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- if .Values.isolateComponents }}
  SE_DISTRIBUTOR_HOST: '{{ include "seleniumGrid.distributor.fullname" . }}.{{ .Release.Namespace }}'
  SE_DISTRIBUTOR_PORT: '{{ .Values.components.distributor.port }}'
  SE_ROUTER_HOST: '{{ include "seleniumGrid.router.fullname" . }}.{{ .Release.Namespace }}'
  SE_ROUTER_PORT: '{{ .Values.components.router.port }}'
{{- else }}
  SE_HUB_HOST: '{{ include "seleniumGrid.hub.fullname" . }}.{{ .Release.Namespace }}'
  SE_HUB_PORT: '{{ .Values.hub.port }}'
{{- end }}
  SE_BASIC_AUTH: '{{ template "seleniumGrid.url.basicAuth" $ }}'
  SE_SUB_PATH: '{{ template "seleniumGrid.url.subPath" $ }}'
  SE_DRAIN_AFTER_SESSION_COUNT: '{{- and (eq (include "seleniumGrid.useKEDA" .) "true") (eq .Values.autoscaling.scalingType "job") | ternary "1" "0" -}}'
  SE_NODE_GRID_URL: '{{ include "seleniumGrid.url" .}}'
  SE_NODE_GRID_GRAPHQL_URL: '{{ include "seleniumGrid.graphqlURL" . }}'
{{- if $.Values.nodeConfigMap.leftoversCleanup.enabled }}
  SE_ENABLE_BROWSER_LEFTOVERS_CLEANUP: 'true'
  {{- with $.Values.nodeConfigMap.leftoversCleanup.jobIntervalInSecs }}
  SE_BROWSER_LEFTOVERS_INTERVAL_SECS: '{{ . }}'
  {{- end }}
  {{- with $.Values.nodeConfigMap.leftoversCleanup.browserElapsedTimeInSecs }}
  SE_BROWSER_LEFTOVERS_PROCESSES_SECS: '{{ . }}'
  {{- end }}
  {{- with $.Values.nodeConfigMap.leftoversCleanup.tmpFilesAfterDays }}
  SE_BROWSER_LEFTOVERS_TEMPFILES_DAYS: '{{ . }}'
  {{- end }}
{{- end }}
{{- $fileProceeded := list -}}
{{- range $path, $_ :=  .Files.Glob $.Values.nodeConfigMap.extraScriptsImportFrom }}
  {{- $fileName := base $path -}}
  {{- $value := index $.Values.nodeConfigMap.extraScripts $fileName -}}
  {{- if empty $value }}
{{- $fileName | nindent 2 -}}: {{- toYaml ($.Files.Get $path) | indent 4 }}
  {{- else }}
{{- $fileName | nindent 2 -}}: {{- toYaml $value | indent 4 }}
  {{- end }}
  {{- $fileProceeded = append $fileProceeded $fileName -}}
{{- end }}
{{- range $fileName, $value := .Values.nodeConfigMap.extraScripts }}
  {{- if not (has $fileName $fileProceeded) }}
{{- $fileName | nindent 2 -}}: {{- toYaml (default "" $value) | indent 4 }}
  {{- end }}
{{- end }}
