{{- if .Values.isolateComponents }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "seleniumGrid.router.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &router_labels
    app: {{ template "seleniumGrid.router.fullname" . }}
    app.kubernetes.io/name: {{ template "seleniumGrid.router.fullname" . }}
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  strategy:
    {{- template "seleniumGrid.updateStrategy" (list $.Values.components.router $.Values.global.seleniumGrid) }}
  replicas: 1
  revisionHistoryLimit: {{ .Values.global.seleniumGrid.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "seleniumGrid.router.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: *router_labels
      annotations:
        checksum/logging-configmap: {{ include (print $.Template.BasePath "/logging-configmap.yaml") . | sha256sum }}
        checksum/server-configmap: {{ include (print $.Template.BasePath "/server-configmap.yaml") . | sha256sum }}
        checksum/router-configmap: {{ include (print $.Template.BasePath "/router-configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    {{- with .Values.components.router.annotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ template "seleniumGrid.serviceAccount.fullname" . }}
      serviceAccount: {{ template "seleniumGrid.serviceAccount.fullname" . }}
      containers:
        - name: {{ template "seleniumGrid.router.fullname" . }}
          {{- $imageTag := default .Values.global.seleniumGrid.imageTag .Values.components.router.imageTag }}
          {{- $imageRegistry := default .Values.global.seleniumGrid.imageRegistry .Values.components.router.imageRegistry }}
          image: {{ printf "%s/%s:%s" $imageRegistry .Values.components.router.imageName $imageTag }}
          imagePullPolicy: {{ .Values.components.router.imagePullPolicy }}
          env:
            - name: SE_OTEL_SERVICE_NAME
              value: '{{ template "seleniumGrid.router.fullname" . }}'
            - name: SE_ROUTER_HOST
              value: '{{ template "seleniumGrid.router.fullname" . }}.{{ .Release.Namespace }}'
            - name: SE_ROUTER_PORT
              value: {{ .Values.components.router.port | quote }}
            - name: SE_DISTRIBUTOR_HOST
              value: '{{ template "seleniumGrid.distributor.fullname" . }}.{{ .Release.Namespace }}'
            - name: SE_DISTRIBUTOR_PORT
              value: {{ .Values.components.distributor.port | quote }}
            - name: SE_SESSIONS_MAP_HOST
              value: '{{ template "seleniumGrid.sessionMap.fullname" . }}.{{ .Release.Namespace }}'
            - name: SE_SESSIONS_MAP_PORT
              value: {{ .Values.components.sessionMap.port | quote }}
            - name: SE_SESSION_QUEUE_HOST
              value: '{{ template "seleniumGrid.sessionQueue.fullname" . }}.{{ .Release.Namespace }}'
            - name: SE_SESSION_QUEUE_PORT
              value: {{ .Values.components.sessionQueue.port | quote }}
            {{- with .Values.components.subPath }}
            - name: SE_SUB_PATH
              value: {{ include "utils.trimTrailingSlash" . | quote }}
            {{- end }}
            {{- if .Values.components.router.disableUI }}
            - name: SE_DISABLE_UI
              value: {{ .Values.components.router.disableUI | quote }}
            {{- end }}
          {{- with .Values.components.extraEnvironmentVariables }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "seleniumGrid.logging.configmap.fullname" . }}
            - configMapRef:
                name: {{ template "seleniumGrid.server.configmap.fullname" . }}
            - secretRef:
                name: {{ template "seleniumGrid.common.secrets.fullname" . }}
            {{- with .Values.components.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- range $fileName, $value := $.Values.routerConfigMap.extraScripts }}
            - name: {{ tpl (default (include "seleniumGrid.router.configmap.fullname" $) $.Values.routerConfigMap.scriptVolumeMountName) $ | quote }}
              mountPath: {{ $.Values.routerConfigMap.extraScriptsDirectory }}/{{ $fileName }}
              subPath: {{ $fileName }}
          {{- end }}
          {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
            - name: {{ include "seleniumGrid.tls.fullname" .  | quote }}
              mountPath: {{ .Values.tls.certVolumeMountPath | quote }}
              readOnly: true
          {{- end }}
          ports:
            - containerPort: {{ .Values.components.router.port }}
              protocol: TCP
        {{- if .Values.components.router.startupProbe.enabled }}
          {{- with .Values.components.router.startupProbe }}
          startupProbe:
          {{- if (ne (include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $)) "{}") }}
            {{- include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $) | nindent 10 }}
          {{- else }}
            httpGet:
              scheme: {{ default (include "seleniumGrid.probe.httpGet.schema" $) .schema }}
              path: {{ .path }}
              port: {{ default ($.Values.components.router.port) .port }}
          {{- end }}
          {{- if (ne (include "seleniumGrid.probe.settings" .) "{}") }}
            {{- include "seleniumGrid.probe.settings" . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.components.router.readinessProbe.enabled }}
          {{- with .Values.components.router.readinessProbe }}
          readinessProbe:
          {{- if (ne (include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $)) "{}") }}
            {{- include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $) | nindent 10 }}
          {{- else }}
            httpGet:
              scheme: {{ default (include "seleniumGrid.probe.httpGet.schema" $) .schema }}
              path: {{ .path }}
              port: {{ default ($.Values.components.router.port) .port }}
          {{- end }}
          {{- if (ne (include "seleniumGrid.probe.settings" .) "{}") }}
            {{- include "seleniumGrid.probe.settings" . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.components.router.livenessProbe.enabled }}
          livenessProbe:
          {{- with .Values.components.router.livenessProbe }}
          {{- if (ne (include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $)) "{}") }}
            {{- include "seleniumGrid.probe.fromUserDefine" (dict "values" . "root" $) | nindent 10 }}
          {{- else if eq $.Values.global.seleniumGrid.defaultComponentLivenessProbe "exec" }}
            exec:
              command: ["bash", "-c", "{{ $.Values.routerConfigMap.extraScriptsDirectory }}/routerProbe.sh Liveness {{ include "seleniumGrid.probe.stdout" $ }}"]
          {{- else }}
            httpGet:
              scheme: {{ default (include "seleniumGrid.probe.httpGet.schema" $) .schema }}
              path: {{ .path }}
              port: {{ default ($.Values.components.router.port) .port }}
          {{- end }}
          {{- if (ne (include "seleniumGrid.probe.settings" .) "{}") }}
            {{- include "seleniumGrid.probe.settings" . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- with .Values.components.router.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.components.router.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.components.router.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.affinity .Values.components.router.affinity }}
      {{- $affinityYaml := default .Values.global.seleniumGrid.affinity .Values.components.router.affinity }}
      affinity: {{- toYaml $affinityYaml | nindent 8 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.topologySpreadConstraints .Values.components.distributor.topologySpreadConstraints }}
      {{- $topologySpreadConstraints := default .Values.global.seleniumGrid.topologySpreadConstraints .Values.components.distributor.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range $constraint := $topologySpreadConstraints }}
        - {{ toYaml $constraint | nindent 10 | trim }}
        {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              app: {{ template "seleniumGrid.router.fullname" $ }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.components.router.tolerations }}
      tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.imagePullSecret .Values.components.router.imagePullSecret }}
      imagePullSecrets:
        - name: {{ default .Values.global.seleniumGrid.imagePullSecret .Values.components.router.imagePullSecret }}
    {{- end }}
    {{- with .Values.components.router.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
      volumes:
        - name: {{ tpl (default (include "seleniumGrid.router.configmap.fullname" $) $.Values.routerConfigMap.scriptVolumeMountName) $ | quote }}
          configMap:
            name: {{ template "seleniumGrid.router.configmap.fullname" $ }}
            defaultMode: {{ $.Values.routerConfigMap.defaultMode }}
      {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
        - name: {{ include "seleniumGrid.tls.fullname" .  | quote }}
          secret:
            secretName: {{ include "seleniumGrid.tls.fullname" .  | quote }}
      {{- end }}
{{- end }}
