{{- if .Values.isolateComponents }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "seleniumGrid.sessionQueue.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &session_queue_labels
    app: selenium-session-queue
    app.kubernetes.io/name: selenium-session-queue
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queue
  template:
    metadata:
      labels: *session_queue_labels
    {{- with .Values.components.sessionQueue.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: selenium-session-queue
          {{- $imageTag := default .Values.global.seleniumGrid.imageTag .Values.components.sessionQueue.imageTag }}
          image: {{ printf "%s:%s" .Values.components.sessionQueue.imageName $imageTag }}
          imagePullPolicy: {{ .Values.components.sessionQueue.imagePullPolicy }}
        {{- with .Values.components.extraEnvironmentVariables }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.busConfigMap.name }}
            {{- with .Values.components.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.components.sessionQueue.port }}
              protocol: TCP
        {{- with .Values.components.sessionQueue.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- with .Values.components.sessionQueue.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.components.sessionQueue.tolerations }}
      tolerations:
        {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.global.seleniumGrid.imagePullSecret .Values.components.sessionQueue.imagePullSecret }}
      imagePullSecrets:
        - name: {{ default .Values.global.seleniumGrid.imagePullSecret .Values.components.sessionQueue.imagePullSecret }}
    {{- end }}
    {{- with .Values.components.sessionQueue.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
{{- end }}
