{{- if and (not $.Values.tls.nameOverride) (or (eq (include "seleniumGrid.ingress.secureConnection" $) "true") (eq (include "seleniumGrid.server.secureConnection" $) "true")) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "restartOnUpdate": "true"
  name: {{ include "seleniumGrid.tls.fullname" . }}
  labels:
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
{{- if and (eq (include "seleniumGrid.ingress.secureConnection" $) "true") $.Values.tls.ingress.generateTLS }}
  {{- $name := default "SeleniumHQ" .Values.tls.ingress.defaultName -}}
  {{- $days := default 365 (.Values.tls.ingress.defaultDays | int) -}}
  {{- $cn := ternary .Values.tls.ingress.defaultCN (tpl .Values.ingress.hostname $) (empty .Values.ingress.hostname) -}}
  {{- $server := genSelfSignedCert $cn ( default nil .Values.tls.ingress.defaultIPList ) ( default nil .Values.tls.ingress.defaultSANList ) $days }}
  tls.crt: {{ $server.Cert | b64enc }}
  tls.key: {{ $server.Key | b64enc }}
{{- else if or (eq (include "seleniumGrid.ingress.secureConnection" $) "true") (eq (include "seleniumGrid.server.secureConnection" $) "true") }}
{{- $fileProceeded := list -}}
{{- range $path, $_ :=  .Files.Glob $.Values.tls.secretFilesImportFrom }}
  {{- $fileName := base $path -}}
  {{- $value := index $.Values.tls.secretFiles $fileName -}}
  {{- if empty $value }}
{{- $fileName | nindent 2 -}}: {{- toYaml ($.Files.Get $path | b64enc) | indent 4 }}
  {{- else }}
{{- $fileName | nindent 2 -}}: {{- toYaml ($value | b64enc) | indent 4 }}
  {{- end }}
  {{- $fileProceeded = append $fileProceeded $fileName -}}
{{- end }}
{{- range $fileName, $value := .Values.tls.secretFiles }}
  {{- if not (has $fileName $fileProceeded) }}
{{- $fileName | nindent 2 -}}: {{- toYaml (default "" $value | b64enc) | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
